---
title: '2019-03-20'
author: "yuenchen"
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
aVector<-c(5,6,7)
a2Vector<-c(5L,6L,7L)
bVector<-c("你好","How are you?")
b<-"你好"
```

```{r}
class(aVector)
class(a2Vector)
class(bVector)
class(b)
```



```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```
```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```

```{r}
studentMajors1 <-c("經濟系", "經濟系", "法律系")

```
```{r}
class(studentMajors)
```

```{r}
class(studentMajors1)
```

```{r}
birthplace <- factor(c("新北", "南部","新北", "台北","台北"))
class(birthplace)
levels(birthplace)
typeof(birthplace)
as.integer(birthplace)
```
```{r}
library(lubridate)
```
```{r}
dtObject<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22") 
)
```

```{r}
bVector<-c("你好","How are you?")
```




```{r}
birthplaces <- factor(c("桃園市","新竹市","澎湖島","台北市","蘭嶼"))
typeof(birthplaces)
levels(birthplaces)
as.integer(birthplaces)
```

```{r}
birth_place <- factor(c("臺東", "台北", "金門"))
typeof(birth_place)
as.integer(birth_place)
```


```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObject<-ymd_hms("2019-03-20 16:58:53") 

class(dtObject)
typeof(dtObject)
as.double(dtObject)
```


```{r}
Sys.timezone()
```

